name: 'Gradle command'
description: 'Configuration actions to run a gradle command in self-hosted runner'
inputs:
  gradle-command:
    description: 'Gradle command to execute'
    required: true
  arguments:
    required: false
    description: 'Gradle options'
    default: ''
  default-arguments:
    required: false
    description: 'Default gradle switches' # Copied from CommonJobProperties.groovy'
    default: |
      --continue -Dorg.gradle.jvmargs=-Xms2g -Dorg.gradle.jvmargs=-Xmx6g \
      -Dorg.gradle.vfs.watch=false -Pdocker-pull-licenses
  max-workers:
   required: false
   description: 'Max number of workers'
   default: 8

runs:
  using: "composite"
  steps:
    - name: Run Gradle Command
      shell: bash
      run: |
        ./gradlew ${{ inputs.gradle-command }} --max-workers=${{ inputs.max-workers }} ${{ inputs.default-arguments }} \
        ${{ inputs.arguments }}

